### ISSUE TITLE
New-M365DSCReportFromConfiguration: not populating

### ISSUE THREAD

**Issue by krugerd** [microsoft/Microsoft365DSC#1845]
#### Details of the scenario you tried and the problem that is occurring
Running New-M365DSCReportFromConfiguration -type Excel -ConfigurationPath C:\ps\file1.ps1 -OutputPath c:\ps\output.xlsx

The onscreen output in PowerShell is "Parsing [x/x]", then local copy of Excel opens on my computer, but only fills out fields A1:C3 with the following:
Component Name, Property, Value
Settings,, default,Value,Personal,
Settings,, default,Value,Non-business data, for personal use only.,

Version of Excel is Microsoft® Excel® for Microsoft 365 MSO (16.0.14326.20850) 32-bit 

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB, fr-CA, fr-FR}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.323.1

**Comment by krugerd** [comment]
![output](https://user-images.githubusercontent.com/99920431/160904658-c44a1f6b-7878-42c1-868b-8f9aa475ee0a.JPG)
jpg attached

**Comment by krugerd** [comment]
closed in error - reopening :)

**Comment by Fuerst2718** [comment]
Similar (nearly empty) output generating HTML (using 1.22.323.1)

Whole Content:
```
<h1>M365Config</h1><div style='width:100%;text-align:center;'><h2>Template Details</h2>
```
![empty-html](https://user-images.githubusercontent.com/70098906/161303428-3e6da950-bd82-4c29-a4d1-6517593fb615.png)

**Comment by Fuerst2718** [comment]
Just checked with -Type JSON -> here we get a completly empty file (M365Config.json)
```
PS C:\Temp> New-M365DSCReportFromConfiguration -Type JSON -ConfigurationPath .\M365Config.ps1 -OutputPath .\M365Config.json; dir


    Directory: C:\Temp


Mode                LastWriteTime         Length Name                                                                                                                                 
----                -------------         ------ ----                                                                                                                                 
-a----       2022-04-03     04:37           1058 ConfigurationData.psd1                                                                                                               
-a----       2022-04-03     04:37            180 M365Config.html                                                                                                                      
-a----       2022-04-03     11:35              0 M365Config.json                                                                                                                      
-a----       2022-04-03     04:37         997870 M365Config.ps1           
```

**Comment by jreinhardtproarch** [comment]
I too can't get a report to generate in Excel or HTML. I have a fresh install of the latest version of the module, and have tried running in both 5.1 and 7.1.6.  My output is as shown below in HTML. It seems to be a conflagging of both EXO Hosted Content Filter policies and Transport Rules, but I've gathered almost all EXO components.

![image](https://user-images.githubusercontent.com/49915885/162475266-ae59ab4e-d086-4e24-acee-c59d9ba1db6d.png)

**Comment by krugerd** [comment]
Issue appears to have been fixed in latest version out today 1.22.413.1!

**Comment by jreinhardtproarch** [comment]
I can confirm. It seems to be functional again.

**Comment by Fuerst2718** [comment]
Can confirm for HTML-Output:
![image](https://user-images.githubusercontent.com/70098906/163564040-9af04a99-b8bc-48b4-8070-14aaa6df79c6.png)

**Comment by IntuneAdmin** [comment]
Can confirm 😬

**Comment by grabery** [comment]
Still doesn't work for me, always empty reports.
Using Microsoft365DSC Module v 1.22.420.1

Did test it with PS 5.1 and 7.2... no success.
Any guess?

**Comment by pl-kyle** [comment]
I can confirm I now have data again.  Is there a way to filter out the row ResourceID?  It is always going to be different and makes the report messy.

**Comment by AbdelmounaimZaidi** [comment]
I have the same outcome Using Microsoft365DSC Module v 1.22.420.1

Did test it with PS 5.1 and 7.2... no success. Feedback much appreciated.

**Comment by ykuijs** [comment]
I just tested this with 1.22.518.1 and it works for me. Is this still applicable?

- If not, please close the issue.
- If so, could you please share the configuration you are trying to create Excel documentation from?

**Comment by krugerd** [comment]
Issue resolve for me as of 1.22.413.1.  Works in current version.  Thanks!

**Comment by Fuerst2718** [comment]
Same Problem again as described above since version 1.22.525.1 (latest working version for me has been 1.22.420.1)

![image](https://user-images.githubusercontent.com/70098906/172058421-92e453c2-08af-4fe3-8d35-6390bab84e63.png)

Content of HTML-File:
```
<!DOCTYPE html><html><body><h1>M365Config</h1><div style='width:100%;text-align:center;'><h2>Template Details</h2>
```
--------- Dependency-Updates done 
```
PS C:\Windows\system32> Update-M365DSCDependencies -Force
Installing DSCParser version {1.3.0.4}
Installing ExchangeOnlineManagement version {2.0.5}
Installing Microsoft.Graph.Applications version {1.9.6}
Installing Microsoft.Graph.Authentication version {1.9.6}
Installing Microsoft.Graph.DeviceManagement version {1.9.6}
Installing Microsoft.Graph.DeviceManagement.Administration version {1.9.6}
Installing Microsoft.Graph.DeviceManagement.Enrolment version {1.9.6}
Installing Microsoft.Graph.Devices.CorporateManagement version {1.9.6}
Installing Microsoft.Graph.Groups version {1.9.6}
Installing Microsoft.Graph.Identity.DirectoryManagement version {1.9.6}
Installing Microsoft.Graph.Identity.Governance version {1.9.6}
Installing Microsoft.Graph.Identity.SignIns version {1.9.6}
Installing Microsoft.Graph.Planner version {1.9.6}
Installing Microsoft.Graph.Teams version {1.9.6}
Installing Microsoft.Graph.Users version {1.9.6}
Installing Microsoft.PowerApps.Administration.PowerShell version {2.0.147}
Installing MicrosoftTeams version {4.4.1}
Installing MSCloudLoginAssistant version {1.0.84}
Installing PnP.PowerShell version {1.10.0}
Installing ReverseDSC version {2.0.0.11}
```
Versioninfo:
```
Machine: SVDE****** (Microsoft Windows NT 10.0.14393.0)
PSVersion: 5.1.14393.4583
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.4583
BuildVersion: 10.0.14393.4583
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
```
Moduleinfo
```
Name              : Microsoft365DSC
Path              : C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.601.1\Microsoft365DSC.psd1
Description       : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online,
                    Exchange, Teams, etc.
Guid              : 39f599a6-d212-4480-83b3-a8ea2124d8cf
Version           : 1.22.601.1
ModuleBase        : C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.601.1
ModuleType        : Manifest
PrivateData       : {PSData}
AccessMode        : ReadWrite
ExportedAliases   : {}
ExportedCmdlets   : {}
ExportedFunctions : {[Add-M365DSCEvent, Add-M365DSCEvent], [Add-M365DSCTelemetryEvent, Add-M365DSCTelemetryEvent],
                    [Assert-M365DSCBlueprint, Assert-M365DSCBlueprint], [Confirm-ImportedCmdletIsAvailable,
                    Confirm-ImportedCmdletIsAvailable]...}
ExportedVariables : {}
NestedModules     : {M365DSCAgent, M365DSCErrorHandler, M365DSCLogEngine, M365DSCPermissions...}
```

**Comment by Fuerst2718** [comment]
No, it did not.
Just done ...
```
PS C:\Windows\system32> Uninstall-M365DSCOutdatedDependencies
Uninstalling Microsoft.Graph.Applications version {1.9.5}
Uninstalling Microsoft.Graph.DeviceManagement version {1.9.5}
Uninstalling Microsoft.Graph.DeviceManagement.Administration version {1.9.5}
Uninstalling Microsoft.Graph.DeviceManagement.Enrolment version {1.9.5}
Uninstalling Microsoft.Graph.Devices.CorporateManagement version {1.9.5}
Uninstalling Microsoft.Graph.Groups version {1.9.5}
Uninstalling Microsoft.Graph.Identity.DirectoryManagement version {1.9.5}
Uninstalling Microsoft.Graph.Identity.Governance version {1.9.5}
Uninstalling Microsoft.Graph.Identity.SignIns version {1.9.5}
Uninstalling Microsoft.Graph.Planner version {1.9.5}
Uninstalling Microsoft.Graph.Teams version {1.9.5}
Uninstalling Microsoft.Graph.Users version {1.9.5}
Uninstalling Microsoft.PowerApps.Administration.PowerShell version {2.0.145}
Uninstalling MicrosoftTeams version {4.3.0}
Uninstalling MicrosoftTeams version {4.2.0}
Uninstalling MSCloudLoginAssistant version {1.0.83}
Uninstalling ReverseDSC version {2.0.0.10}
Checking Microsoft.Graph.Authentication
Uninstalling Microsoft.Graph.Authentication version {1.9.5}
```
... restarted the job and now I see a well filled html-file (html-content ok ) ...

```
07.06.2022  19:51         3.178.550 M365Config.html
07.06.2022  19:51         1.075.730 M365Config.ps1
```
