### ISSUE TITLE
Compilation errors occurred while processing configuration 'M365TenantConfig'.

### ISSUE THREAD

**Issue by DscEngineer** [microsoft/Microsoft365DSC#4091]
### Description of the issue

I've been working on DSC for past few months and already deployed Exchange, Teams, SPO but in Intune I am getting this error while trying to create MOF file. Please help me fix this as I have a lot of data in this policy and I can not create it Manually.

```
IntuneDeviceConfigurationEndpointProtectionPolicyWindows10\M365TenantConfig.ps1:229 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule

Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'remoteAccess,wireless,lan' is not supported or valid for property 'InterfaceTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only supported values: notConfigured, remoteAccess, wireless, lan.

Compilation errors occurred while processing configuration 'M365TenantConfig'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
```

### Microsoft 365 DSC Version

1.23.1213.1

### Which workloads are affected

other

### The DSC configuration

```powershell
IntuneDeviceConfigurationEndpointProtectionPolicyWindows10
```

**Comment by DscEngineer** [comment]
am able to fix this but it still did not resolve the issue I was expecting it will. I was trying to configure Endpoint security | Firewall Configuration settings where I have 100 of rules configured and I cannot find any component for DSC on the portal. Can someone please share the same as it is very important setting and it is impossible to do manual configuration of 100+ firewall rules.

**Comment by ykuijs** [comment]
Hi @DscEngineer, could you please share the configuration you are using? I think there might be an issue in there.

**Comment by William-Francillette** [comment]
@DscEngineer, @ykuijs 
I had a look and there is a disparity between the schema and actual API which is the cause of the issue
The schema (which the source from where the resource is generated) defines the parameter as an enum with 4 possible values
![image](https://github.com/microsoft/Microsoft365DSC/assets/79221284/92e79d90-cb2f-423c-b89b-806394145942)
![image](https://github.com/microsoft/Microsoft365DSC/assets/79221284/ebce11a7-8326-47ea-9b59-dc132bf17c42)
 
However the API and Intune allows multiple values separated with a coma
![image](https://github.com/microsoft/Microsoft365DSC/assets/79221284/0a7e9c80-2ddc-4239-80a2-9968cdc9478e)

2 attributes will be impacted: 
InterfaceTypes
ProfileTypes

I will have to update the resource definition and update the type of those 2 parameters from string to string[] and also update Get-TargetResource and Set-TargetResource to parse those attributes accordingly
@ykuijs, will that be considered a breaking change?
If so, we can remove the validateSet/ValueMap and consider those attribute as string and don't verify the value (easy fix) 

Let me know what you prefer?

**Comment by William-Francillette** [comment]
Oh I actually just understood the IsFlags attribute in the schema and where I was mistaken in the DRG - looks like those enum will accept multiple values and be parsed with a coma in the policy 🤷‍♂️
Something more to add to the DRG and schema parser!

**Comment by ricmestre** [comment]
@William-Francillette If the API only mentions the enum but it doesn't show up as a collection then it's a single string which happens to have multiple values separated by commas and not actually a string array.

This is the same problem I encountered with IntuneDeviceConfigurationPolicyMacOS where I tried to fix in #4099, and now I have to fix that fix in #4106, where property *UpdateDelayPolicy* is defined in M365DSC as a String[] but it should have been setup as a String.

**Comment by William-Francillette** [comment]
The root of the issue is how to manage those flag enums and how strict the validation (if any ) should be
I can see 3 different paths we could take:
1- Keep them as simple string and don't validate the value (simplest - no breaking change)
2- Keep them as string but validate that the values are included in the value set (no breaking change)
3- Use string collection and parse the value during Get and Set (Breaking change for most resources using flags)

@NikCharlebois, @ykuijs, @andikrueger, @ricmestre Any preference?

**Comment by ykuijs** [comment]
My preference is to use option 3. That is what is most clear for users and makes the most sense. However since that is a breaking change, we cannot implement that right now. So as a temporary workaround, we can implement option 2 now and switch to option 3 in April.

**Comment by William-Francillette** [comment]
Cool I will try to create a repeatable process for option 2 and create an issue to show how to fix similar issues
Next step would be to create a repeatable process for option 3 which could be tested on IntuneDeviceConfigurationPolicyMacOS
I have in mind to create the parser methods in M365DRGUtil  (ConvertTo and ConvertFrom) so that it involves a minimal resource code change

**Comment by William-Francillette** [comment]
@ricmestre I've sorted IntuneDeviceConfigurationEndpointProtectionPolicyWindows10
I can have a look at implemented option 3 for IntuneDeviceConfigurationPolicyMacOS if you're not working on it

**Comment by ricmestre** [comment]
@william-francillette In this case I think option 3 wouldn't apply to *IntuneDeviceConfigurationPolicyMacOS* since it's essentially the reverse of what's happening here?

Basically what's happening on *IntuneDeviceConfigurationPolicyMacOS* has *UpdateDelayPolicy* set as String[] where the API expects String so I fixed it by joining the array into a single string, still not quite right see my PR #4106 for further details, but what I got from @ykuijs is that it's more natural in these cases to have an array and then deal with the API internally like I'm doing on that PR? Did I get that right?

**Comment by FabienTschanz** [comment]
I'll close this one. Currently, I didn't find any resources that still have an issue with it. It's more natural to use option 3 and parse it internally to what the api expects.
